// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59B7D_J1F-N3jwOZXUWSRqqS82znZXi0',
    appId: '1:202652545803:android:6e89b5979e4afa7387a80e',
    messagingSenderId: '202652545803',
    projectId: 'scrapie-35cf8',
    storageBucket: 'scrapie-35cf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DEv_jMqSh51XKD-E9y2JEAWQ1yrNekA',
    appId: '1:202652545803:ios:ca501e3702fa28fa87a80e',
    messagingSenderId: '202652545803',
    projectId: 'scrapie-35cf8',
    storageBucket: 'scrapie-35cf8.appspot.com',
    iosClientId: '202652545803-eut2c7u2l1cemc4cpk1spkvj8pc7kb2b.apps.googleusercontent.com',
    iosBundleId: 'com.masoodismail.scrapie',
  );
}
